{
  flake = _: {
    nixosModules.${baseNameOf ./.} = {
      pkgs,
      lib,
      ...
    }: {
      hm = {
        home.packages = lib.attrValues {
          inherit
            (pkgs)
            krabby
            ;
        };

        programs.otter-launcher = {
          enable = true;
        };

        # source config due to problems with unicode in nix to toml conversion
        xdg.configFile."otter-launcher/config.toml".text =
          builtins.readFile ./config.toml
          |> builtins.replaceStrings ["@username@"] [lib.userName]
          |> (s: "# Generated by function in modules/cli/otter-launcher/default.nix\n" + s);
      };
    };
  };
}
