[Interface]
PrivateKey = uAfY2i7CFDpRBw9R9I/s8o0Ap3aSpivj/0cvCNF8rlk=
Address = 192.168.100.100/32  # Любой IP в сети eth3

[Peer]
PublicKey = 9yTXXq8xR3K1tNwor5tGmLXVriR0CWSo41U4A3Frq38=
Endpoint = 192.168.100.1:51820  # Шлюз в сети eth3
AllowedIPs = 0.0.0.0/0, ::/0    # Весь трафик
PersistentKeepalive = 25
