{
  windowRules = [
    # "opacity 0.89 override 0.89 override, title:^(.*)$"
    "float, title:^(blueberry.py)$"
    "float, title:^(steam)$"
    "float, title:^(guifetch)$"
    "tile, class:(dev.warp.Warp)"
    "tile, title:^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$"
    "center, title:^(Open File)(.*)$"
    "center, title:^(Select a File)(.*)$"
    "center, title:^(Choose wallpaper)(.*)$"
    "center, title:^(Open Folder)(.*)$"
    "center, title:^(Save As)(.*)$"
    "center, title:^(Library)(.*)$"
    "center, title:^(File Upload)(.*)$"
    "center, title:^(Extract)(.*)$"
    "center, title:^(Wine configuration)(.*)$"
    "center, title:^(Blobdrop)(.*)$"
    "float, title:^(Blobdrop)(.*)$"

    "float, class:com.free.clipse"
    "size 900 652, class:com.free.clipse"
    "stayfocused, class:com.free.clipse"
    "noborder, class:com.free.clipse"

    "float, class:com.free.otter-launcher"
    "size 600 500, class:com.free.otter-launcher"
    "stayfocused, class:com.free.otter-launcher"
    "noborder, class:com.free.otter-launcher"

    "float, class:com.free.fsel"
    "size 600 500, class:com.free.fsel"
    "stayfocused, class:com.free.fsel"
    "noborder, class:com.free.fsel"

    "float, class:com.free.kalker"
    "size 600 500, class:com.free.kalker"
    "stayfocused, class:com.free.kalker"
    "noborder, class:com.free.kalker"

    "float, class:it.mijorus.smile"
    "size 600 800, class:it.mijorus.smile"
    "stayfocused, class:it.mijorus.smile"
    "noborder, class:it.mijorus.smile"

    "float, class:com.note.tjournal"
    "size 1200 800, class:com.note.tjournal"
    "stayfocused, class:com.note.tjournal"
    "noborder, class:com.note.tjournal"

    "keepaspectratio, title:^(Picture(-| )in(-| )[Pp]icture)$"
    "move 73% 72%,title:^(Picture(-| )in(-| )[Pp]icture)$"
    "size 25%, title:^(Picture(-| )in(-| )[Pp]icture)$"
    "float, title:^(Picture(-| )in(-| )[Pp]icture)$"
    "pin, title:^(Picture(-| )in(-| )[Pp]icture)$"

    "float,title:^(Open File)(.*)$"
    "float,title:^(Select a File)(.*)$"
    "float,title:^(Choose wallpaper)(.*)$"
    "float,title:^(Open Folder)(.*)$"
    "float,title:^(Save As)(.*)$"
    "float,title:^(Library)(.*)$"
    "float,title:^(File Upload)(.*)$"
    "float,title:^(Extract)(.*)$"

    "workspace 2, class:^(zen-beta)$"
    "monitor 0, class:^(com.ayugram.desktop)$"

    "immediate,title:^(.*\\.exe)$"
    "immediate,class:(steam_app)"

    "noshadow,floating:0"
    "bordercolor rgba(C6C5D6AA) rgba(C6C5D677),pinned:1"
  ];

  layerRules = [
    "xray 1, .*"
    "noanim, walker"
    "noanim, selection"
    "noanim, overview"
    "noanim, anyrun"
    "noanim, indicator.*"
    "noanim, osk"
    "noanim, hyprpicker"
    "noanim, ^(dms)$"
    "blur, shell:*"
    "ignorealpha 0.6, shell:*"

    "noanim, noanim"
    "blur, gtk-layer-shell"
    "ignorezero, gtk-layer-shell"
    "blur, launcher"
    "ignorealpha 0.5, launcher"
    "blur, notifications"
    "ignorealpha 0.69, notifications"

    "animation slide left, sideleft.*"
    "animation slide right, sideright.*"
    "blur, session"

    "blur, bar"
    "ignorealpha 0.6, bar"
    "blur, corner.*"
    "ignorealpha 0.6, corner.*"
    "blur, dock"
    "ignorealpha 0.6, dock"
    "blur, indicator.*"
    "ignorealpha 0.6, indicator.*"
    "blur, overview"
    "ignorealpha 0.6, overview"
    "blur, cheatsheet"
    "ignorealpha 0.6, cheatsheet"
    "blur, sideright"
    "ignorealpha 0.6, sideright"
    "blur, sideleft"
    "ignorealpha 0.6, sideleft"
    "blur, indicator*"
    "ignorealpha 0.6, indicator*"
    "blur, osk"
    "ignorealpha 0.6, osk"
  ];
}
