{
  imports = [
    ./easyeffects/easyeffects.nix
    ./ghostty.nix
    ./hyprland/hyprland.nix
    ./hyprland/hyprpanel.nix
    ./hyprland/hyprlock.nix
    ./niri/niri.nix
    ./kitty.nix
    ./mpv.nix
    ./nixcord.nix
    ./theming.nix
    ./xdg.nix
    ./waybar/waybar.nix
    ./zen-browser/zen-browser.nix
    ./gaming.nix
    ./davinci.nix
    ./hyprscope/hyprscope.nix
  ];
}
