---
name: Mirror to Codeberg & Tangled
run-name: mirror to codeberg & tangled
permissions:
  contents: read
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: push to codeberg
        env:
          GIT_SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
          GIT_SSH_KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |-
          set +x  # Prevent echoing sensitive data in debug mode
          eval $(ssh-agent -s)
          echo "$GIT_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$GIT_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          git remote add codeberg ssh://git@codeberg.org/angeldust/nixos-config.git
          git remote add tangled git@tangled.org:did:plc:p35cbenhih5vk25dufk3fjns
          git push codeberg main --force
          git push tangled main --force
